### ISSUE TITLE
jcenter deprecated

### ISSUE THREAD

**Issue by MatthewMatt83** [rugovit/EventLiveData#1]
Hello, 
I was wondering if you have already planned on migrating your cool library on some other repo since jcenter has been officially deprecated, as stated here: https://developer.android.com/studio/build/jcenter-migration 

Thank you in advance, 
F

**Comment by rugovit** [comment]
Hi Matt, 

I will migrate it as soon as I get some free time in next week or so.
 From  JFrog :

> Artifactory installations with remote repositories configured against JCenter, GoCenter, and ChartCenter will not be affected by this sunset

so you as a user will not be affected with this JFrog shutdown.
